### ISSUE TITLE
Weight Modulation

### ISSUE THREAD

**Issue by ZJJTSL** [ZhimingZo/Modulated-GCN#9]
hello, thanks for your great work! Here are some my confusions. What's the difference between Weight Modulation and sem_ch_graph_conv in SemGCN?  In table 2, what's the difference between sparsity and l1-loss? In your code implementation, the sparsity constraint is the same as what mentioned in Sec3.4. Looking forward your reply,thanks!

**Comment by ZhimingZo** [comment]
Simply speaking, SemGCN focuses on the feature aggregation process by multiplying a learnable matrix on the affinity matrix A, while Modulated GCN focuses on the feature transformation process.  Weight modulation learns different modulation vectors for different nodes so that the feature transformations of different nodes are disentangled. sparsity is an L1-regularizer imposed on the affinity matrix. L1-loss is measured between the GT and output 3D joints coordinates. They are quite different.

**Comment by jianlai123-123** [comment]
Can you tell me how to test on the MPI-INF-3DHP dataset. Thank you. @ZJJTSL
